// Generated by `npm run openapi` from openapi.json. Do not edit.

export type Outline = {
  id: string;
  object: "outline";
  status: "draft" | "confirmed" | "in_use";
  drafting: {
    status: "running" | "done" | "failed";
    pages: number;
    pages_read: number;
    failures: {
      page: number;
      reason: string;
    }[];
  } | null;
  source_pages: {
    page: number;
    image_url: string | null;
  }[];
  nodes: OutlineNode[];
  errors: {
    code: "missing_range" | "inverted_range" | "outside_parent" | "sibling_overlap" | "multiple_answer_keys" | "duplicate_id" | "gap";
    node_id: string | null;
    message: string;
  }[];
  warnings: {
    code: "missing_range" | "inverted_range" | "outside_parent" | "sibling_overlap" | "multiple_answer_keys" | "duplicate_id" | "gap";
    node_id: string | null;
    message: string;
  }[];
  created_at: string;
  expires_at: string;
};

export type OutlineNode = {
  id: string;
  name: string;
  level: string | null;
  printed_pages: {
    from: number;
    to: number;
  } | null;
  kind: "content" | "answer_key";
  external_ref: string | null;
  children: OutlineNode[];
};

export type OutlineNodeInput = {
  id?: string;
  name: string;
  level?: string | null;
  printed_pages?: {
    from: number;
    to: number;
  } | null;
  kind?: "content" | "answer_key";
  external_ref?: string | null;
  children?: OutlineNodeInput[];
};

export type CreateOutlineRequest = {
  source: {
    type: "manual";
    nodes: OutlineNodeInput[];
  } | {
    type: "pdf";
    upload_id: string;
  } | {
    type: "images";
    upload_ids: string[];
  } | {
    type: "book_pages";
    upload_id: string;
    from: number;
    to: number;
  };
};

export type ReplaceOutlineRequest = {
  nodes: OutlineNodeInput[];
};

export type Document = {
  id: string;
  object: "document";
  type: "questions" | "explanation" | "both";
  status: "queued" | "rendering" | "awaiting_offset" | "processing" | "completed" | "completed_with_errors" | "failed";
  revision: number;
  outline_id: string;
  created_at: string;
  expires_at: string;
  progress: {
    pages_total: number | null;
    pages_read: number;
  };
  usage: {
    /** Pages billed: the pages read, written when the job ends */
    pages: number;
  };
  error: string | null;
  offset: {
    printed_from: number;
    pdf_from: number;
    confirmed: boolean;
  }[];
  warning: {
    /** same_file_processed | … */
    code: string;
    message: string;
    document_id: string | null;
    processed_at: string | null;
  } | null;
  offset_agreement: number | null;
  stimuli: {
    id: string;
    kind: "passage" | "diagram" | "table";
    text: string;
    node_id: string;
    pages: number[];
    image: {
      url: string;
      pdf_page: number;
    } | null;
  }[];
  questions: {
    id: string;
    type: "multiple_choice" | "fill_blank" | "true_false";
    number: string | null;
    text: string;
    options: {
      key: string;
      text: string;
    }[];
    correct: string[];
    accepted_answers: string[];
    answer_source: ("book" | "marked" | "model" | "review") | null;
    node_id: string;
    node_path: string[];
    external_ref: string | null;
    stimulus_id: string | null;
    locator: {
      pdf_page: number;
      printed_page: number | null;
    };
    idea_tag: string | null;
    math_direction: ("ltr" | "rtl") | null;
    image: {
      url: string;
      pdf_page: number;
    } | null;
    review_required: boolean;
    review_reason: string | null;
    confidence: number;
  }[];
  explanation?: {
    id: string;
    node_id: string;
    node_path: string[];
    external_ref: string | null;
    heading: string;
    markdown: string;
    math_direction: ("ltr" | "rtl") | null;
    figures: {
      url: string;
      pdf_page: number;
    }[];
    pages: {
      pdf: number[];
      printed: number[];
    };
    review_required: boolean;
    review_reason: string | null;
  }[];
  skipped: {
    neither: number;
    off_type: number;
  };
  failures: {
    /** unmapped_page | offset_break | image_unreadable | incomplete_question | part_failed (clients treat unknown reasons as a generic failure) */
    reason: string;
    locator: {
      pdf_page: number;
      printed_page: number | null;
    };
    detail: string | null;
    page_image: {
      url: string;
      pdf_page: number;
    } | null;
  }[];
};

export type CreateDocumentRequest = {
  outline_id: string;
  type: "questions" | "explanation" | "both";
  source: {
    upload_id: string;
  } | {
    upload_ids: string[];
  };
  language?: "ar" | "en";
  offset?: "auto" | "confirm";
  webhook_url?: string;
};

export type CreatedDocument = {
  id: string;
  object: "document";
  status: "queued" | "rendering" | "awaiting_offset" | "processing" | "completed" | "completed_with_errors" | "failed";
  warning: {
    /** same_file_processed | … */
    code: string;
    message: string;
    document_id: string | null;
    processed_at: string | null;
  } | null;
};

export type ConfirmOffsetRequest = {
  segments?: {
    printed_from: number;
    pdf_from: number;
  }[];
};

export type CreateRevisionRequest = {
  base_revision: number;
  changes: Change[];
};

export type Change = {
  op: "edit_question";
  id: string;
  text?: string;
  type?: "multiple_choice" | "fill_blank" | "true_false";
  options?: {
    key: string;
    text: string;
  }[];
  correct?: string[];
  accepted_answers?: string[];
} | {
  op: "accept_answer";
  id: string;
} | {
  op: "set_stimulus";
  id: string;
  stimulus_id: string | null;
} | {
  op: "move";
  id: string;
  node_id: string;
} | {
  op: "delete";
  id: string;
} | {
  op: "edit_chunk";
  id: string;
  heading?: string;
  markdown?: string;
} | {
  op: "recrop";
  id: string;
  figure?: number;
  box: CropBox;
} | {
  op: "place_block";
  pdf_page: number;
  block_id: string;
  node_id: string;
} | {
  op: "dismiss_failure";
  index: number;
};

export type CropBox = {
  x: number;
  y: number;
  w: number;
  h: number;
};

export type CreateUploadRequest = {
  filename: string;
  content_type: "application/pdf" | "image/jpeg" | "image/png" | "image/webp";
  size: number;
};

export type Upload = {
  id: string;
  object: "upload";
  upload_url: string;
  method: "PUT";
  expires_at: string;
};

export type Usage = {
  object: "usage";
  balance: number;
  ledger: {
    kind: "grant" | "hold" | "release" | "usage";
    pages: number;
    document_id: string | null;
    note: string | null;
    created_at: string;
  }[];
};

export type WebhookSecret = {
  object: "webhook_secret";
  secret: string;
};

export type WebhookPayload = {
  id: string;
  object: "document";
  status: "queued" | "rendering" | "awaiting_offset" | "processing" | "completed" | "completed_with_errors" | "failed";
  revision: number;
};

export type CreateSessionRequest = {
  outline_id?: string;
  document_id?: string;
  return_url: string;
  webhook_url?: string;
};

export type Session = {
  object: "session";
  url: string;
  expires_at: string;
};

export type Error = {
  error: {
    code: string;
    message: string;
    details?: unknown;
  };
};
