-- Up Migration
-- E-15: people, sessions and organisation membership (Better Auth). The
-- organisation model is Engines' own `organisations` table (ADR 0002).
-- Generated by Better Auth's migration planner, then reviewed.

ALTER TABLE organisations ADD COLUMN slug text;
UPDATE organisations SET slug = id WHERE slug IS NULL;
ALTER TABLE organisations ALTER COLUMN slug SET NOT NULL;
ALTER TABLE organisations ADD COLUMN logo text;
ALTER TABLE organisations ADD COLUMN metadata text;
CREATE UNIQUE INDEX organisations_slug_uidx ON organisations (slug);

CREATE TABLE users (
  id text PRIMARY KEY,
  name text NOT NULL,
  email text NOT NULL UNIQUE,
  email_verified boolean NOT NULL,
  image text,
  -- The owner's account, set by a one-off script (E-20). Checked on the server.
  super_admin boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sessions (
  id text PRIMARY KEY,
  expires_at timestamptz NOT NULL,
  token text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL,
  ip_address text,
  user_agent text,
  user_id text NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  active_organization_id text
);
CREATE INDEX sessions_user_id_idx ON sessions (user_id);

CREATE TABLE accounts (
  id text PRIMARY KEY,
  account_id text NOT NULL,
  provider_id text NOT NULL,
  user_id text NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  access_token text,
  refresh_token text,
  id_token text,
  access_token_expires_at timestamptz,
  refresh_token_expires_at timestamptz,
  scope text,
  password text,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL
);
CREATE INDEX accounts_user_id_idx ON accounts (user_id);

CREATE TABLE verifications (
  id text PRIMARY KEY,
  identifier text NOT NULL,
  value text NOT NULL,
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX verifications_identifier_idx ON verifications (identifier);

CREATE TABLE members (
  id text PRIMARY KEY,
  org_id text NOT NULL REFERENCES organisations (id) ON DELETE CASCADE,
  user_id text NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  role text NOT NULL,
  created_at timestamptz NOT NULL
);
CREATE INDEX members_org_id_idx ON members (org_id);
CREATE INDEX members_user_id_idx ON members (user_id);

CREATE TABLE invitations (
  id text PRIMARY KEY,
  org_id text NOT NULL REFERENCES organisations (id) ON DELETE CASCADE,
  email text NOT NULL,
  role text,
  status text NOT NULL,
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  inviter_id text NOT NULL REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX invitations_org_id_idx ON invitations (org_id);
CREATE INDEX invitations_email_idx ON invitations (email);

-- Keys made on the page record who made them. The page itself acts through a
-- built-in key per organisation, so its documents share the organisation's
-- caps like any other key's.
ALTER TABLE api_keys ADD COLUMN created_by text REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE api_keys ADD COLUMN built_in boolean NOT NULL DEFAULT false;
CREATE UNIQUE INDEX api_keys_one_built_in ON api_keys (org_id) WHERE built_in AND revoked_at IS NULL;

-- Down Migration
DROP INDEX api_keys_one_built_in;
ALTER TABLE api_keys DROP COLUMN built_in;
ALTER TABLE api_keys DROP COLUMN created_by;
DROP TABLE invitations;
DROP TABLE members;
DROP TABLE verifications;
DROP TABLE accounts;
DROP TABLE sessions;
DROP TABLE users;
DROP INDEX organisations_slug_uidx;
ALTER TABLE organisations DROP COLUMN metadata;
ALTER TABLE organisations DROP COLUMN logo;
ALTER TABLE organisations DROP COLUMN slug;
