// TypeScript types for the typed client (E-21), generated from openapi.json's
// schemas. They use a small part of JSON Schema (object, array, enum, const,
// anyOf/oneOf, $ref, nullable types), so a small generator does, with no
// dependency. `npm run openapi` writes client/src/schema.ts with it.

type Schema = Record<string, unknown>;

export function schemaTypes(components: Record<string, Schema>): string {
  const out = [
    "// Generated by `npm run openapi` from openapi.json. Do not edit.",
    "",
  ];
  for (const [name, schema] of Object.entries(components)) {
    const doc = comment(schema, "");
    out.push(`${doc}export type ${name} = ${typeOf(schema, "")};`, "");
  }
  return `${out.join("\n").trimEnd()}\n`;
}

function comment(schema: Schema, indent: string): string {
  const text = schema["description"];
  return typeof text === "string" && text !== ""
    ? `${indent}/** ${text.replace(/\*\//g, "* /").replace(/\n/g, " ")} */\n`
    : "";
}

function typeOf(schema: Schema, indent: string): string {
  const ref = schema["$ref"];
  if (typeof ref === "string") return ref.split("/").at(-1) ?? "unknown";
  if ("const" in schema) return JSON.stringify(schema["const"]);
  const enumValues = schema["enum"];
  if (Array.isArray(enumValues))
    return enumValues.map((v) => JSON.stringify(v)).join(" | ");
  for (const key of ["anyOf", "oneOf"]) {
    const options = schema[key];
    if (Array.isArray(options))
      return (options as Schema[])
        .map((o) => wrap(typeOf(o, indent)))
        .join(" | ");
  }
  const type = schema["type"];
  if (Array.isArray(type))
    return (type as string[])
      .map((t) => typeOf({ ...schema, type: t }, indent))
      .join(" | ");
  switch (type) {
    case "string":
      return "string";
    case "integer":
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "null":
      return "null";
    case "array":
      return `${wrap(typeOf((schema["items"] ?? {}) as Schema, indent))}[]`;
    case "object":
      return objectType(schema, indent);
    default:
      return "unknown";
  }
}

function objectType(schema: Schema, indent: string): string {
  const properties = (schema["properties"] ?? {}) as Record<string, Schema>;
  const entries = Object.entries(properties);
  if (entries.length === 0) return "Record<string, unknown>";
  const required = new Set((schema["required"] ?? []) as string[]);
  const inner = `${indent}  `;
  const lines = entries.map(
    ([name, value]) =>
      `${comment(value, inner)}${inner}${key(name)}${required.has(name) ? "" : "?"}: ${typeOf(value, inner)};`,
  );
  return `{\n${lines.join("\n")}\n${indent}}`;
}

/** A union (even of objects) inside an array or another union needs brackets. */
function wrap(type: string): string {
  return topLevelUnion(type) ? `(${type})` : type;
}

/** Whether `|` joins the type at its outer level, not only inside braces. */
function topLevelUnion(type: string): boolean {
  let depth = 0;
  for (let i = 0; i < type.length; i++) {
    const ch = type[i];
    if (ch === "{" || ch === "(" || ch === "[") depth++;
    else if (ch === "}" || ch === ")" || ch === "]") depth--;
    else if (depth === 0 && type.startsWith(" | ", i)) return true;
  }
  return false;
}

/** A property name as TypeScript takes it: quoted unless it's an identifier. */
function key(name: string): string {
  return /^[A-Za-z_$][\w$]*$/.test(name) ? name : JSON.stringify(name);
}
