#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# E-02 (issue #3): walled-off Google Cloud resources for Engines.
#
# Run from anywhere:   bash scripts/setup-gcp.sh
# Safe to re-run: every step checks what already exists and skips it.
# Local values land in .env at the repo root (git-ignored). Production secrets
# go to Secret Manager only, never to .env.

TOTAL_STAGES=13

cd "$(dirname "$0")/.."

# ── Engines helpers (built on the library above) ──────────────────────────

# On Windows Git Bash the plain `gcloud` shim can't find Python; point it at
# the SDK's bundled interpreter. Captured output has its CRs stripped.
if ! gcloud version >/dev/null 2>&1; then
  _sdk_python="$(dirname "$(command -v gcloud || echo .)")/../platform/bundledpython/python.exe"
  [[ -f "$_sdk_python" ]] && export CLOUDSDK_PYTHON="$_sdk_python"
fi
gc() { gcloud "$@" | tr -d '\r'; }

# winpath PATH: a temp-file path gcloud's Windows Python can open.
winpath() { if command -v cygpath >/dev/null 2>&1; then cygpath -w "$1"; else printf '%s' "$1"; fi; }

# ask_default KEY "Prompt" DEFAULT: like ask, falling back to DEFAULT.
ask_default() {
  ask "$1" "$2 [default: $3]"
  if [[ -z "${!1}" ]]; then printf -v "$1" '%s' "$3"; fi
}

SECRETS_MADE=()

# put_secret NAME VALUE: create the engines-* secret if missing, add a new
# version only when the value changed, and let engines-runtime read it.
put_secret() {
  local name="$1" value="$2" current tmp
  if [[ -z "$value" ]] && gc secrets versions access latest --secret="$name" --project="$PROJECT" >/dev/null 2>&1; then
    note "$name: nothing entered, keeping the stored value"
  elif [[ -z "$value" ]]; then
    warn "no value for $name, skipped"
    SKIPPED+=("Secret Manager: $name (no value given)")
    return 0
  else
    if ! gc secrets describe "$name" --project="$PROJECT" >/dev/null 2>&1; then
      gc secrets create "$name" --project="$PROJECT" \
        --replication-policy=automatic --labels=service=engines >/dev/null
    fi
    current=$(gc secrets versions access latest --secret="$name" --project="$PROJECT" 2>/dev/null || true)
    if [[ "$current" == "$value" ]]; then
      note "$name already holds this value"
    else
      tmp=$(mktemp); chmod 600 "$tmp"; printf '%s' "$value" > "$tmp"
      if ! gc secrets versions add "$name" --project="$PROJECT" --data-file="$(winpath "$tmp")" >/dev/null; then
        rm -f "$tmp"; return 1
      fi
      rm -f "$tmp"
      printf '  %s✓ stored%s %s in Secret Manager\n' "$GREEN" "$RESET" "$name"
    fi
  fi
  gc secrets add-iam-policy-binding "$name" --project="$PROJECT" \
    --member="serviceAccount:$SA_EMAIL" --role=roles/secretmanager.secretAccessor >/dev/null
  SECRETS_MADE+=("$name")
}

# sql_wait INSTANCE: block until no admin operation is running on it.
sql_wait() {
  local op
  for op in $(gc sql operations list --instance="$1" --project="$PROJECT" \
                --filter="status!=DONE" --format="value(name)"); do
    gc sql operations wait "$op" --project="$PROJECT" --timeout=unlimited >/dev/null
  done
}

# setup_sql INSTANCE ENV: a small Postgres server with an `engines` database
# and user, labelled service=engines. The user's password is generated here
# (never typed) and kept in Secret Manager as engines-db-password-ENV.
setup_sql() {
  local inst="$1" env="$2" extra=() users pw token
  if [[ "$env" == prod ]]; then extra=(--backup --deletion-protection); else extra=(--no-backup); fi

  if gc sql instances describe "$inst" --project="$PROJECT" >/dev/null 2>&1; then
    note "$inst already exists"
  else
    confirm "Create Cloud SQL server $inst ($PG_VERSION, $SQL_TIER, $REGION)? It bills until deleted." \
      || { SKIPPED+=("Cloud SQL server $inst"); return 0; }
    say "Creating $inst: this usually takes 5–10 minutes…"
    gc sql instances create "$inst" --project="$PROJECT" --region="$REGION" \
      --database-version="$PG_VERSION" --edition=enterprise --tier="$SQL_TIER" \
      --availability-type=zonal "${extra[@]}" >/dev/null
  fi
  sql_wait "$inst"

  if ! gc sql databases describe engines --instance="$inst" --project="$PROJECT" >/dev/null 2>&1; then
    gc sql databases create engines --instance="$inst" --project="$PROJECT" >/dev/null
  fi

  pw=$(gc secrets versions access latest --secret="engines-db-password-$env" --project="$PROJECT" 2>/dev/null || true)
  users=$(gc sql users list --instance="$inst" --project="$PROJECT" --format="value(name)")
  if [[ -z "$pw" ]]; then
    pw=$(openssl rand -hex 24)
    if grep -qx engines <<<"$users"; then
      gc sql users set-password engines --instance="$inst" --project="$PROJECT" --password="$pw" >/dev/null
    fi
  fi
  if ! grep -qx engines <<<"$users"; then
    gc sql users create engines --instance="$inst" --project="$PROJECT" --password="$pw" >/dev/null
  fi
  put_secret "engines-db-password-$env" "$pw"
  if [[ "$env" == dev ]]; then write_env ENGINES_DB_DEV_PASSWORD "$pw"; fi

  # gcloud GA has no label flag for Cloud SQL, so set userLabels over REST.
  sql_wait "$inst"
  token=$(gc auth print-access-token)
  if curl -fsS -X PATCH "https://sqladmin.googleapis.com/v1/projects/$PROJECT/instances/$inst" \
       -H "Authorization: Bearer $token" -H "Content-Type: application/json" \
       -d "{\"settings\":{\"userLabels\":{\"service\":\"engines\",\"env\":\"$env\"}}}" >/dev/null; then
    sql_wait "$inst"
    printf '  %s✓ labelled%s %s service=engines env=%s\n' "$GREEN" "$RESET" "$inst" "$env"
  else
    warn "couldn't label $inst; add service=engines under Labels on its console page"
    SKIPPED+=("label Cloud SQL $inst with service=engines, env=$env")
  fi
}

# ask_openrouter_key ENV VAR: walk through making one capped key, into $VAR.
ask_openrouter_key() {
  local env="$1" var="$2"
  open_url "https://openrouter.ai/settings/keys"
  step "Click Create API Key. Name it: engines-$env"
  step "Set Credit limit to the cap for $env (e.g. \$10 for dev). It must not be blank: blank means unlimited."
  step "Click Create, then copy the key (starts sk-or-v1-). It is shown only once."
  ask_secret "$var" "Paste the engines-$env key:"
  if [[ -n "${!var}" && "${!var}" != sk-or-* ]]; then
    warn "that doesn't look like an OpenRouter key (sk-or-…); storing it anyway"
  fi
  put_secret "engines-openrouter-key-$env" "${!var}"
}

# ──────────────────────────────────────────────────────────────────────────

banner "Engines: walled-off Google Cloud resources (E-02)"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight: project, region, APIs"
command -v gcloud >/dev/null 2>&1 || { warn "gcloud not found; install the Google Cloud CLI first"; exit 1; }
for tool in openssl curl; do
  command -v "$tool" >/dev/null 2>&1 || { warn "$tool not found; install it first"; exit 1; }
done
say "Signed in as: $(gc config get account 2>/dev/null)"
ask_default GCP_PROJECT_ID "Almahdi's Google Cloud project ID" "$(gc config get project 2>/dev/null)"
ask_default GCP_REGION "Region (Almahdi's database lives in europe-west3)" "europe-west3"
PROJECT="$GCP_PROJECT_ID"
REGION="$GCP_REGION"
ask_default PG_VERSION "Postgres version" "POSTGRES_17"
ask_default SQL_TIER "Cloud SQL machine tier (shared-core, cheapest)" "db-f1-micro"
[[ -n "$PROJECT" ]] || { warn "no project ID"; exit 1; }
BILLING_ACCOUNT=$(gc billing projects describe "$PROJECT" --format="value(billingAccountName)")
BILLING_ACCOUNT="${BILLING_ACCOUNT#billingAccounts/}"
[[ -n "$BILLING_ACCOUNT" ]] || { warn "billing is not enabled on $PROJECT"; exit 1; }
SA_EMAIL="engines-runtime@$PROJECT.iam.gserviceaccount.com"
PROD_DB=engines-prod-db
DEV_DB=engines-dev-db
BUCKETS=(engines-uploads engines-pages engines-results)
note "Engines creates only new engines-* resources. It never touches almahdi-db,"
note "Almahdi's buckets or Almahdi's secrets."
confirm "Set up Engines in project $PROJECT (billing account $BILLING_ACCOUNT)?" || exit 1
write_env GCP_PROJECT_ID "$PROJECT"
write_env GCP_REGION "$REGION"
write_env PG_VERSION "$PG_VERSION"
write_env SQL_TIER "$SQL_TIER"
say "Enabling APIs (already-enabled ones are a no-op; Vertex AI is for later)…"
gc services enable sqladmin.googleapis.com storage.googleapis.com secretmanager.googleapis.com \
  iam.googleapis.com cloudresourcemanager.googleapis.com cloudbilling.googleapis.com \
  billingbudgets.googleapis.com aiplatform.googleapis.com --project="$PROJECT"
printf '  %s✓ APIs enabled%s\n' "$GREEN" "$RESET"
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Service account engines-runtime"
say "Engines runs as its own identity. It gets roles only on engines-* resources,"
say "granted one by one in the next stages, and nothing at project level except"
say "a Cloud SQL client role limited to Engines' own two servers."
if gc iam service-accounts describe "$SA_EMAIL" --project="$PROJECT" >/dev/null 2>&1; then
  note "$SA_EMAIL already exists"
else
  gc iam service-accounts create engines-runtime --project="$PROJECT" \
    --display-name="Engines runtime" \
    --description="Engines (service=engines). Roles only on engines-* resources." >/dev/null
  printf '  %s✓ created%s %s\n' "$GREEN" "$RESET" "$SA_EMAIL"
fi
note "Service accounts can't carry labels (and cost nothing), so this one has none."
write_env ENGINES_RUNTIME_SA "$SA_EMAIL"
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Cloud SQL: Engines production server"
say "A new, separate server: $PROD_DB. Not almahdi-db."
setup_sql "$PROD_DB" prod
PROD_CONN=$(gc sql instances describe "$PROD_DB" --project="$PROJECT" --format="value(connectionName)" 2>/dev/null || true)
write_env ENGINES_DB_PROD_CONNECTION "$PROD_CONN"
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Cloud SQL: Engines dev server"
say "A second, separate server for dev: $DEV_DB. Dev never uses a production server."
setup_sql "$DEV_DB" dev
DEV_CONN=$(gc sql instances describe "$DEV_DB" --project="$PROJECT" --format="value(connectionName)" 2>/dev/null || true)
write_env ENGINES_DB_DEV_CONNECTION "$DEV_CONN"
write_env ENGINES_DB_NAME engines
write_env ENGINES_DB_USER engines
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Cloud SQL access for engines-runtime (Engines' servers only)"
say "Cloud SQL roles can only be granted at project level, so this grant carries"
say "an IAM condition that limits it to $PROD_DB and $DEV_DB. It gives no access"
say "to almahdi-db. engines-runtime also has no database user or password there."
SQL_CONDITION="expression=resource.service == 'sqladmin.googleapis.com' && (resource.name == 'projects/$PROJECT/instances/$PROD_DB' || resource.name == 'projects/$PROJECT/instances/$DEV_DB'),title=engines-sql-only,description=Cloud SQL client on Engines servers only"
gc projects add-iam-policy-binding "$PROJECT" --member="serviceAccount:$SA_EMAIL" \
  --role=roles/cloudsql.client --condition="$SQL_CONDITION" >/dev/null
printf '  %s✓ granted%s roles/cloudsql.client (condition: engines-sql-only)\n' "$GREEN" "$RESET"
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Buckets with lifecycle rules"
say "uploads are deleted after 2 days (a safety net: jobs delete them themselves);"
say "page images and results after 30 days."
for bucket in "${BUCKETS[@]}"; do
  if [[ "$bucket" == engines-uploads ]]; then age=2; else age=30; fi
  if gc storage buckets describe "gs://$bucket" --project="$PROJECT" >/dev/null 2>&1; then
    note "gs://$bucket already exists"
  else
    gc storage buckets create "gs://$bucket" --project="$PROJECT" --location="$REGION" \
      --default-storage-class=STANDARD --uniform-bucket-level-access --public-access-prevention >/dev/null
    printf '  %s✓ created%s gs://%s\n' "$GREEN" "$RESET" "$bucket"
  fi
  rules=$(mktemp)
  printf '{"rule":[{"action":{"type":"Delete"},"condition":{"age":%s}}]}' "$age" > "$rules"
  gc storage buckets update "gs://$bucket" --project="$PROJECT" \
    --lifecycle-file="$(winpath "$rules")" --update-labels=service=engines >/dev/null
  rm -f "$rules"
  gc storage buckets add-iam-policy-binding "gs://$bucket" \
    --member="serviceAccount:$SA_EMAIL" --role=roles/storage.objectAdmin >/dev/null
  printf '  %s✓%s gs://%s: delete after %s days, service=engines, engines-runtime objectAdmin\n' \
    "$GREEN" "$RESET" "$bucket" "$age"
done
write_env ENGINES_BUCKET_UPLOADS engines-uploads
write_env ENGINES_BUCKET_PAGES engines-pages
write_env ENGINES_BUCKET_RESULTS engines-results
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "OpenRouter: capped key for Engines dev"
say "Make a new key for Engines only. Don't reuse Almahdi's OpenRouter key."
ask_openrouter_key dev OPENROUTER_API_KEY
if [[ -n "$OPENROUTER_API_KEY" ]]; then write_env OPENROUTER_API_KEY "$OPENROUTER_API_KEY"; fi
pause

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "OpenRouter: capped key for Engines production"
say "A second key with its own cap. It goes to Secret Manager only, not .env."
note "Re-running? Press Enter at the prompt to keep the key already stored."
ask_openrouter_key prod OPENROUTER_KEY_PROD
pause

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Google sign-in: check the consent screen (branding)"
say "The OAuth consent screen (app name, logo, support email) belongs to the whole"
say "project, so Engines and Almahdi share it."
open_url "https://console.cloud.google.com/auth/branding?project=$PROJECT"
step "If the page shows an existing app name: leave it exactly as it is."
step "If it asks you to get started: App name Engines, your support email,"
step "Audience External, your contact email, agree, then Create."
warn "Changing an existing app name also changes what Almahdi's users see."
pause "Press Enter once branding exists"

# ── 10 ────────────────────────────────────────────────────────────────────
stage "Google sign-in: OAuth client for Engines"
ask_default OAUTH_DEV_ORIGIN "Local dev origin of Engines' page" "http://localhost:3000"
OAUTH_REDIRECT="$OAUTH_DEV_ORIGIN/api/auth/callback/google"
note "Redirect path is Better Auth's default for Google; E-15 can change it."
open_url "https://console.cloud.google.com/auth/clients/create?project=$PROJECT"
step "Application type: Web application. Name: Engines"
step "Authorized JavaScript origins → Add URI: $OAUTH_DEV_ORIGIN"
step "Authorized redirect URIs → Add URI: $OAUTH_REDIRECT"
step "Click Create. Copy the Client ID and the Client secret from the dialog"
step "(the secret may not be shown again)."
ask GOOGLE_CLIENT_ID "Paste the Client ID (ends .apps.googleusercontent.com):"
ask_secret GOOGLE_CLIENT_SECRET "Paste the Client secret:"
write_env OAUTH_DEV_ORIGIN "$OAUTH_DEV_ORIGIN"
write_env GOOGLE_CLIENT_ID "$GOOGLE_CLIENT_ID"
write_env GOOGLE_CLIENT_SECRET "$GOOGLE_CLIENT_SECRET"
put_secret engines-google-oauth-client-secret "$GOOGLE_CLIENT_SECRET"
pause

# ── 11 ────────────────────────────────────────────────────────────────────
stage "Monthly budget alert for service=engines"
CURRENCY=$(gc billing accounts describe "$BILLING_ACCOUNT" --format="value(currencyCode)" 2>/dev/null || true)
CURRENCY="${CURRENCY:-USD}"
say "Covers Google Cloud spend on everything labelled service=engines. OpenRouter"
say "spend is capped separately by the key limits you just set."
budgets=$(gc billing budgets list --billing-account="$BILLING_ACCOUNT" --format="value(displayName)")
if grep -qx engines-monthly <<<"$budgets"; then
  note "budget engines-monthly already exists"
else
  ask_default BUDGET_AMOUNT "Monthly budget in $CURRENCY" "50"
  write_env BUDGET_AMOUNT "$BUDGET_AMOUNT"
  gc billing budgets create --billing-account="$BILLING_ACCOUNT" \
    --display-name=engines-monthly --budget-amount="$BUDGET_AMOUNT" \
    --calendar-period=month --filter-projects="projects/$PROJECT" \
    --filter-labels=service=engines \
    --threshold-rule=percent=0.5 --threshold-rule=percent=0.9 --threshold-rule=percent=1.0 \
    --threshold-rule=percent=1.0,basis=forecasted-spend >/dev/null
  printf '  %s✓ created%s budget engines-monthly (%s %s/month, alerts at 50/90/100%%)\n' \
    "$GREEN" "$RESET" "$BUDGET_AMOUNT" "$CURRENCY"
fi
note "Alerts email the billing account's admins by default."
pause

# ── 12 ────────────────────────────────────────────────────────────────────
stage "Check: engines-runtime has no role on Almahdi resources"
LEAKS=()
say "Project-level roles held by engines-runtime:"
gc projects get-iam-policy "$PROJECT" --flatten=bindings \
  --filter="bindings.members:serviceAccount:$SA_EMAIL" \
  --format="table(bindings.role,bindings.condition.title)" | sed 's/^/    /'
unconditioned=$(gc projects get-iam-policy "$PROJECT" --flatten=bindings \
  --filter="bindings.members:serviceAccount:$SA_EMAIL" \
  --format="csv[no-heading](bindings.role,bindings.condition.title)" | awk -F, '$2 == "" { print $1 }')
if [[ -n "$unconditioned" ]]; then LEAKS+=("project-wide role without a condition: $unconditioned"); fi
for bucket in $(gc storage buckets list --project="$PROJECT" --format="value(name)"); do
  [[ "$bucket" == engines-* ]] && continue
  policy=$(gc storage buckets get-iam-policy "gs://$bucket" --format=json)
  if grep -qF "$SA_EMAIL" <<<"$policy"; then
    LEAKS+=("bucket gs://$bucket")
  fi
done
for secret in $(gc secrets list --project="$PROJECT" --format="value(name)"); do
  secret="${secret##*/}"
  [[ "$secret" == engines-* ]] && continue
  policy=$(gc secrets get-iam-policy "$secret" --project="$PROJECT" --format=json)
  if grep -qF "$SA_EMAIL" <<<"$policy"; then
    LEAKS+=("secret $secret")
  fi
done
if (( ${#LEAKS[@]} )); then
  warn "engines-runtime can reach Almahdi resources:"
  for l in "${LEAKS[@]}"; do note "  - $l"; done
  SKIPPED+=("remove engines-runtime from: ${LEAKS[*]}")
else
  printf '  %s✓ no binding on any Almahdi bucket or secret, and no project-wide role%s\n' "$GREEN" "$RESET"
  note "The only project-level grant is cloudsql.client under condition engines-sql-only."
fi
pause

# ── 13 ────────────────────────────────────────────────────────────────────
stage "Record resource names on issue #3"
RESOURCES_DOC=docs/infra/gcp-resources.md
mkdir -p "$(dirname "$RESOURCES_DOC")"
{
  printf '## Engines Google Cloud resources (E-02)\n\n'
  printf 'Names only: no secret values. Every resource carries `service=engines` where GCP allows labels.\n\n'
  printf '| What | Name |\n|---|---|\n'
  printf '| Project / region | `%s` / `%s` |\n' "$PROJECT" "$REGION"
  printf '| Service account | `%s` |\n' "$SA_EMAIL"
  printf '| Cloud SQL, production | `%s` (connection `%s`) |\n' "$PROD_DB" "$PROD_CONN"
  printf '| Cloud SQL, dev | `%s` (connection `%s`) |\n' "$DEV_DB" "$DEV_CONN"
  printf '| Database / user | `engines` / `engines` on both servers |\n'
  printf '| Buckets | `gs://engines-uploads` (2 days), `gs://engines-pages` (30 days), `gs://engines-results` (30 days) |\n'
  printf '| Secrets | %s |\n' "$(printf '`%s` ' "${SECRETS_MADE[@]}" | sed 's/ $//')"
  printf '| OAuth client ID | `%s` (redirect `%s`) |\n' "$GOOGLE_CLIENT_ID" "$OAUTH_REDIRECT"
  printf '| Budget | `engines-monthly`, filtered on `service=engines` |\n'
  printf '| Vertex AI | `aiplatform.googleapis.com` enabled, not used yet |\n\n'
  printf 'Isolation: `engines-runtime` holds `roles/cloudsql.client` only under the IAM condition `engines-sql-only` (Engines'"'"' two servers). It has no role on `almahdi-db`, Almahdi'"'"'s buckets or Almahdi'"'"'s secrets, and no database user there. The OAuth consent screen (branding) is project-wide and shared with Almahdi.\n'
} > "$RESOURCES_DOC"
printf '  %s✓ wrote%s %s\n\n' "$GREEN" "$RESET" "$RESOURCES_DOC"
sed 's/^/    /' "$RESOURCES_DOC"
printf '\n'
open_url "https://github.com/almahdiplatform1712006/engines/issues/3"
step "Paste the block above as a comment on issue #3 (it's in $RESOURCES_DOC too)."
note "The repo is public: the block holds names and IDs only, never secret values."
pause "Press Enter once it's posted"

finish
